language: node_js
node_js:
    - "node"
before_install:
    - npm install -g grunt-cli
    - npm install grunt@0.4.1
    - npm install grunt-contrib-sass@0.7.4
    - npm install grunt-contrib-watch@1.0.0
install:
    - npm install
before_script:
    - grunt sass