language: node_js
node_js:
    - "node"
before_install:
    - npm install -g grunt-cli
    - npm install grunt@0.4.5 grunt-contrib-sass@0.7.4 grunt-postcss cssnano grunt-contrib-jshint grunt-phantomas grunt-penthouse --save-dev
    - npm remove grunt-autoprefixer
    - npm install grunt-postcss autoprefixer --save-dev
    - npm update caniuse-db
    - gem install compass
install:
    - npm install
script: 
    - grunt sass -v
    - grunt postcss -v
    - grunt jshint -v