language: node_js
node_js:
    - "node"
before_install:
    - npm install -g grunt-cli
    - npm install grunt@0.4.5
    - npm install grunt-contrib-sass@0.7.4
    - npm install grunt-contrib-watch@1.0.0
    - npm install grunt-postcss
    - npm install pixrem
    - npm install cssnano
    - npm remove grunt-autoprefixer
    - npm install grunt-postcss autoprefixer
    - npm update caniuse-db
    - gem install compass
install:
    - npm install
"scripts": {
        "clean": "grunt postcss",
        "buildsass": "grunt sass"
    }