language: node_js
node_js:
    - "8.0.0"
before_install:
    - npm install -g grunt-cli
    - npm install grunt@0.4.5 grunt-contrib-sass@0.7.4 cssnano grunt-contrib-jshint --save-dev
    - npm --save install postcss-scss
    - npm install phantomjs2
    - npm remove grunt-autoprefixer
    - npm install grunt-postcss autoprefixer --save-dev
    - npm install grunt-casperjs --save-dev
    - npm update caniuse-db
    - gem install compass
install:
    - npm install
script: 
    - grunt sass
    - grunt postcss
    - grunt jshint