language: node_js
node_js:
    - "node"
cache:
    - node_modules/
before_install:
    - npm install -g grunt-cli
    - npm install grunt@0.4.5
    - npm install grunt-contrib-sass@0.7.4
    - npm install grunt-postcss
    - npm install cssnano
    - npm install phantomjs2
    - npm install grunt-contrib-jshint --save-dev
    - npm install grunt-phantomas --save-dev
    - npm remove grunt-autoprefixer
    - npm install grunt-postcss autoprefixer
    - npm update caniuse-db
    - gem install compass
install:
    - npm install
script: 
    - grunt postcss
    - grunt sass